package me.clip.deluxetags;

import java.util.List;
import java.util.UUID;
import java.util.Map;
import java.io.File;
import java.util.concurrent.Executor;
import java.util.concurrent.Executors;
import java.util.function.Consumer;
import me.clip.deluxetags.storage.MySqlSelectionStore;
import me.clip.deluxetags.storage.Selection;
import me.clip.deluxetags.storage.SelectionService;
import me.clip.deluxetags.storage.SelectionStore;
import me.clip.deluxetags.storage.StorageSettings;
import me.clip.deluxetags.storage.YamlSelectionStore;

import me.clip.deluxetags.commands.TagCommand;
import me.clip.deluxetags.commands.TagTabCompleter;
import me.clip.deluxetags.config.ConfigWrapper;
import me.clip.deluxetags.config.Lang;
import me.clip.deluxetags.config.TagConfig;
import me.clip.deluxetags.config.StorageConfig;
import org.bukkit.configuration.file.YamlConfiguration;
import me.clip.deluxetags.gui.GUIHandler;
import me.clip.deluxetags.gui.GUIOptions;
import me.clip.deluxetags.gui.TagGUI;
import me.clip.deluxetags.listeners.ChatFormatListener;
import me.clip.deluxetags.listeners.ChatListener;
import me.clip.deluxetags.listeners.JoinListener;
import me.clip.deluxetags.listeners.PlayerListener;
import me.clip.deluxetags.placeholders.TagPlaceholders;
import me.clip.deluxetags.tags.DeluxeTag;
import me.clip.deluxetags.tags.DeluxeTagCategory;
import me.clip.deluxetags.tags.DeluxeTagsHandler;
import me.clip.deluxetags.tasks.CleanupTask;
import me.clip.deluxetags.updater.UpdateChecker;
import me.clip.deluxetags.utils.MsgUtils;
import me.clip.deluxetags.utils.SchedulerCompat;
import me.clip.deluxetags.utils.SchedulerCompat.TaskHandle;
import me.clip.placeholderapi.PlaceholderAPI;
import org.bukkit.Bukkit;
import org.bukkit.command.PluginCommand;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;
import org.bukkit.plugin.java.JavaPlugin;

/**
 * DeluxeTags plugin
 * 
 * @author Ryan McCarthy
 */
public class DeluxeTags extends JavaPlugin {

	private static final DeluxeTag DUMMY_TAG = new DeluxeTag(420691337, "", "", "");
	private static final String NO_TAG_IDENTIFIER = Selection.NO_TAG;

	private DeluxeTagsHandler tagsHandler;
	private TagConfig cfg;
	private ConfigWrapper messages;
	private ConfigWrapper playerFile;
	private GUIHandler guiHandler;
	private GUIOptions guiOptions;
	private TaskHandle cleanupTask = null;
	private TaskHandle storageTask;
	private SelectionService selections;
	private boolean mysqlStorage;
	private Map<String, Object> storageSettings;

	private static boolean papi;

	@Override
	public void onEnable() {
		tagsHandler = new DeluxeTagsHandler(this);

		cfg = new TagConfig(this);
		cfg.loadDefConfig();
		StorageSettings settings;
		try {
			YamlConfiguration storageConfig = loadStorageConfig();
			settings = new StorageSettings(storageConfig);
			storageSettings = StorageSettings.snapshot(storageConfig);
		} catch (Exception e) {
			getLogger().severe("Could not load mysql.yml (" + e.getClass().getSimpleName()
					+ "). Check the storage configuration and file permissions.");
			Bukkit.getPluginManager().disablePlugin(this);
			return;
		}
		mysqlStorage = settings.mysql;

		reloadFormattingOptions();

		cfg.loadCategories();
		int loaded = cfg.loadTags();
		if (loaded == 1) {
			getLogger().info("1 tag loaded");
		} else {
			getLogger().info(loaded + " tags loaded");
		}

		playerFile = new ConfigWrapper(this, "userdata", "player_tags.yml");
		
		if (!mysqlStorage && !new File(getDataFolder(), "userdata/player_tags.yml").exists()) {
			playerFile.createNewFile(null, "DeluxeTags player_tags.yml\nDo not edit this file!");
		}
		
		cleanupTask = SchedulerCompat.runAsyncTimer(this, new CleanupTask(this), 20L*300, 20L*300);
		
		guiOptions = new GUIOptions(this);
		
		guiHandler = new GUIHandler(this);
		
		Bukkit.getPluginManager().registerEvents(guiHandler, this);

		PluginCommand command = getCommand("tags");
		if (command != null) command.setExecutor(new TagCommand(this));
		if (command != null) command.setTabCompleter(new TagTabCompleter(this));
		
		Bukkit.getPluginManager().registerEvents(new PlayerListener(this), this);
		
		Bukkit.getPluginManager().registerEvents(new JoinListener(this), this);
		
		messages = new ConfigWrapper(this, null, "messages.yml");

		messages.createNewFile("Loading DeluxeTags messages.yml",
				"DeluxeTags messages.yml\nEdit the plugin messages to your liking!");

		loadMessages();
		SelectionStore store = mysqlStorage
				? new MySqlSelectionStore(settings, getDataFolder(), message -> getLogger().info(message))
				: new YamlSelectionStore(new File(getDataFolder(), "userdata/player_tags.yml"));
		Executor worker = mysqlStorage ? Executors.newSingleThreadExecutor(task -> {
			Thread thread = new Thread(task, "DeluxeTags-storage");
			thread.setDaemon(true);
			return thread;
		}) : Runnable::run;
		selections = new SelectionService(store, worker, task -> {
			if (!isEnabled()) return;
			if (SchedulerCompat.isGlobalThread()) task.run();
			else SchedulerCompat.runGlobal(this, task);
		}, this::refreshPlayerSelection, message -> getLogger().info(message));
		selections.poll();
		for (Player player : Bukkit.getOnlinePlayers()) loadPlayerSelection(player);
		storageTask = SchedulerCompat.runGlobalTimer(this, selections::poll,
				settings.interval * 20L, settings.interval * 20L);
		
		papi = Bukkit.getPluginManager().getPlugin("PlaceholderAPI") != null;

		if (cfg.papiChat()) {
			getLogger().info("PAPI Chat enabled. This means your chat plugin will use placeholders to fetch the tags!");
		} else {
			if (cfg.formatChat()) {
				Bukkit.getPluginManager().registerEvents(new ChatFormatListener(this), this);
			}

			Bukkit.getPluginManager().registerEvents(new ChatListener(this), this);

			getLogger().info("You are not using a chat plugin that supports PlaceholderAPI!");
			getLogger().info("DeluxeTags will listen to the AsyncPlayerChatEvent to provide compatibility for some chat plugins.");
		}

		if (papi) {
			new TagPlaceholders(this).register();
		}
		
		if (cfg.checkUpdates()) {
			new UpdateChecker(this).fetch();
		}
	}
	
	@Override
	public void onDisable() {
		if (storageTask != null) storageTask.cancel();
		if (selections != null) selections.close();
		if (cleanupTask != null) {
			cleanupTask.cancel();
			cleanupTask = null;	
		}
		
		if (tagsHandler != null) tagsHandler.unloadData();
		TagGUI.unload();
		
		guiOptions = null;
	}

	public DeluxeTagsHandler getTagsHandler() {
		return tagsHandler;
	}

	public TagConfig getCfg() {
		return cfg;
	}

	public DeluxeTag getDummyTag() {
		return DUMMY_TAG;
	}

	public GUIHandler getGUIHandler() {
		return guiHandler;
	}

	public GUIOptions getGuiOptions() {
		return guiOptions;
	}

	public ConfigWrapper getPlayerFile() {
		return playerFile;
	}

	public ConfigWrapper getLangFile() {
		return messages;
	}

	public static boolean papi() {
		return papi;
	}

    /** Cached in MySQL mode; this method never performs network I/O. */
    public String getSavedTagIdentifier(String uuid) {
        if (selections == null) return null;
        try { return selections.getIdentifier(UUID.fromString(uuid)); }
        catch (IllegalArgumentException e) { return null; }
    }

    public boolean hasExplicitNoTag(String uuid) {
        return NO_TAG_IDENTIFIER.equals(getSavedTagIdentifier(uuid));
    }

    public boolean isMySqlStorage() { return mysqlStorage; }

    public boolean isSelectionLoaded(UUID uuid) {
        return selections != null && selections.isLoaded(uuid);
    }

    public void loadPlayerSelection(Player player) {
        tagsHandler.removeActiveTagFromPlayer(player.getUniqueId());
        if (selections != null) selections.join(player.getUniqueId(), cfg.loadTagOnJoin());
    }

    public void unloadPlayerSelection(Player player) {
        if (selections != null) selections.quit(player.getUniqueId());
        tagsHandler.removeActiveTagFromPlayer(player.getUniqueId());
    }

    private void refreshPlayerSelection(UUID uuid) {
        Player player = Bukkit.getPlayer(uuid);
        if (player == null) return;
        tagsHandler.removeActiveTagFromPlayer(uuid);
        tagsHandler.updateTagForPlayer(player);
    }

    /** Completion runs on the server thread, only for the same player session. */
    public void saveTagIdentifierAsync(UUID uuid, String identifier, Consumer<SelectionService.Result> completion) {
        if (!SchedulerCompat.isGlobalThread()) {
            SchedulerCompat.runGlobal(this, () -> saveTagIdentifierAsync(uuid, identifier, completion));
            return;
        }
        if (selections == null) completion.accept(SelectionService.Result.UNAVAILABLE);
        else selections.write(uuid, identifier, completion);
    }

    public void selectTag(Player target, String identifier, CommandSender sender, Runnable success) {
        saveTagIdentifierAsync(target.getUniqueId(), identifier, result -> {
            if (sender instanceof Player && !((Player) sender).isOnline()) return;
            if (result == SelectionService.Result.SUCCESS) {
                success.run();
                return;
            }
            Lang message = result == SelectionService.Result.BUSY ? Lang.STORAGE_BUSY
                    : result == SelectionService.Result.LOADING ? Lang.STORAGE_LOADING : Lang.STORAGE_UNAVAILABLE;
            MsgUtils.msg(sender, message.getConfigValue(null));
        });
    }

    /** Compatibility wrapper. Use saveTagIdentifierAsync to observe persistence failures. */
    public void saveTagIdentifier(String uuid, String tagIdentifier) {
        if (!SchedulerCompat.isGlobalThread()) {
            SchedulerCompat.runGlobal(this, () -> saveTagIdentifier(uuid, tagIdentifier));
            return;
        }
        if (selections == null) return;
        try {
            selections.write(UUID.fromString(uuid), tagIdentifier, false, result -> {
                if (result != SelectionService.Result.SUCCESS) {
                    getLogger().warning("Could not save player tag: " + result.name());
                }
            });
        } catch (IllegalArgumentException e) {
            getLogger().warning("Ignored player selection write with an invalid UUID.");
        }
    }

    public void removeSavedTag(String uuid) {
        if (!SchedulerCompat.isGlobalThread()) {
            SchedulerCompat.runGlobal(this, () -> removeSavedTag(uuid));
            return;
        }
        try {
            UUID id = UUID.fromString(uuid);
            boolean explicitNoTag = Bukkit.getPlayer(id) != null && tagsHandler.getPlayerActiveTag(id) == DUMMY_TAG;
            saveTagIdentifier(uuid, explicitNoTag ? NO_TAG_IDENTIFIER : null);
        } catch (IllegalArgumentException ignored) { }
    }

    public void clearSavedTag(String uuid) {
        if (mysqlStorage || getSavedTagIdentifier(uuid) != null) saveTagIdentifier(uuid, null);
    }

    public void removeSavedTags(List<UUID> uuids) {
        if (uuids != null) for (UUID uuid : uuids) clearSavedTag(uuid.toString());
    }

    private YamlConfiguration loadStorageConfig() throws java.io.IOException, org.bukkit.configuration.InvalidConfigurationException {
        return StorageConfig.load(new File(getDataFolder(), "mysql.yml"));
    }

    public void reloadSelectionStorage(CommandSender sender) {
        try {
            if (!storageSettings.equals(StorageSettings.snapshot(loadStorageConfig()))) {
                MsgUtils.msg(sender, Lang.STORAGE_RESTART.getConfigValue(null));
            }
        } catch (Exception e) {
            MsgUtils.msg(sender, Lang.STORAGE_CONFIG_ERROR.getConfigValue(null));
            getLogger().warning("Could not reload mysql.yml (" + e.getClass().getSimpleName()
                    + "). The current storage remains active.");
        }
        if (!mysqlStorage) {
            selections.reloadYaml();
            playerFile.reloadConfig();
            for (Player player : Bukkit.getOnlinePlayers()) selections.join(player.getUniqueId(), true);
        } else {
            for (Player player : Bukkit.getOnlinePlayers()) refreshPlayerSelection(player.getUniqueId());
            selections.poll();
        }
    }

	public void loadMessages() {
		Lang.setFile(messages.getConfig());

		for (final Lang value : Lang.values()) {
			messages.getConfig().addDefault(value.getPath(), value.getDefault());
		}

		messages.getConfig().options().copyDefaults(true);
		messages.saveConfig();
	}

	public void reloadGUIOptions() {
		guiOptions = new GUIOptions(this);
	}

	public void reloadFormattingOptions() {
		final boolean useLegacyHexPattern = cfg.legacyHex();
		final boolean useMiniMessage = cfg.useMiniMessage();

		MsgUtils.setPattern(useLegacyHexPattern);
		MsgUtils.setMiniMessage(useMiniMessage);

		if (useLegacyHexPattern) {
			getLogger().info("Using legacy hex colors format: &#aaFF00");
		} else {
			getLogger().info("Using standard hex colors format: #aaFF00");
		}

		if (useMiniMessage) {
			getLogger().info("MiniMessage formatting enabled for tags, messages, and GUI text.");
		}
	}

	public String setPlaceholders(Player p, String s, DeluxeTag tag) {
		return setPlaceholders(p, s, tag, DeluxeTagCategory.ALL_IDENTIFIER);
	}

	public String setPlaceholders(Player p, String s, DeluxeTag tag, String categoryIdentifier) {
		if (tag == null) {
			tag = this.getTagsHandler().getPlayerActiveTag(p);
		}
		
		if (tag == null) {
			tag = DUMMY_TAG;
		}

		List<String> tags = this.getTagsHandler().getPlayerAvailableTagIdentifiers(p);
		String tagId = tag.getIdentifier() != null ? tag.getIdentifier() : "";
		String amount = tags != null ? String.valueOf(tags.size()) : "0";
		String categoryAmount = amount;
		if (categoryIdentifier != null && !categoryIdentifier.trim().isEmpty()) {
			categoryAmount = String.valueOf(this.getTagsHandler().getPlayerAvailableTagIdentifiers(p, categoryIdentifier).size());
		}
		String availability = cfg.getTagAvailabilityPlaceholder(tag.hasPermissionToUse(p));

		s = s
			.replace("%player%", p.getName())
			.replace("{player}", p.getName())
			.replace("%displayname%", p.getDisplayName())
			.replace("{displayname}", p.getDisplayName())
			.replace("%deluxetags_tag%", tag.getDisplayTag(p))
			.replace("{deluxetags_tag}", tag.getDisplayTag(p))
			.replace("%deluxetags_identifier%", tagId)
			.replace("{deluxetags_identifier}", tagId)
			.replace("%deluxetags_description%", tag.getDescription(p))
			.replace("{deluxetags_description}", tag.getDescription(p))
			.replace("%deluxetags_amount%", amount)
			.replace("{deluxetags_amount}", amount)
			.replace("%deluxetags_category_amount%", categoryAmount)
			.replace("{deluxetags_category_amount}", categoryAmount)
			.replace("%deluxetags_available%", availability)
			.replace("{deluxetags_available}", availability);
		
		if (papi) {
			s = PlaceholderAPI.setPlaceholders(p, s);
		}

		return MsgUtils.color(s);
	}
}
